name: C/C++ CI

on:
  push:
    branches: [ "main-ci" ]

jobs:

  build-test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix: 
        config: 
          - name: "Windows (MinGW)"
            # artifact: ozy2.exe
            # build_type: Release
            #cc: gcc
            #cxx: g++
            cc: C:\mingw-w64-9.0.0\bin\gcc
            cxx: C:\mingw-w64-9.0.0\bin\g++
            os: [self-hosted, windows]
            
    steps:
    - name: "Current configs ECHO:"
      shell: cmd
      run: |
        echo "Matrix OS: ${{ matrix.config.os }}"
        echo "Context: ${{ toJSON(github) }}"
      
    - name: "Checkout repo branch"
      uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: "Setup GCC buildfiles with CMake"
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles"
      # cd ..
      
    - name: "Compile with MinGW"
      shell: cmd
      run: cmake --build build
      
      
        
        
        
        
        
        
        
