name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      # this cancels all other jobs in the matrix if any of them fails
      # when set to "true", otherwise let each of them build as normal
      fail-fast: false
      matrix: 
        config: 
          - name: "Windows (MinGW-w64)"
            # artifact: ozy2.exe
            build_type: Release
            cc: gcc
            cxx: g++
            os: [self-hosted, windows]
            
    steps:
    
    - name: "Checkout repo branch"
      uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: "Setup GCC buildfiles with CMake"
      shell: cmd
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
      
    - name: "Compile with MinGW"
      shell: cmd
      run: cmake --build build

    - name: "Push output binaries as artifact"
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.config.name }}
        path: artifacts/
      
      
        
        
        
        
        
        
        
