name: C/C++ CI

on:
  push:
    branches: [ "main-ci" ]

jobs:

  build-test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix: 
        config: 
          - name: "Windows (MinGW)"
            # artifact: ozy2.exe
            # build_type: Release
            cc: gcc
            cxx: g++
            os: [self-hosted, windows]
            
    steps:
    - shell: cmd
      run: 'echo "Matrix OS: ${{ matrix.os }}"'
      
    - name: "Checkout repo branch"
      uses: actions/checkout@v3
    
    - name: "Setup CMake"
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.16.x'      
