name: C/C++ CI

on:
  push:
    branches: [ "main-ci" ]

jobs:

  build-test:
    name: ${ { matrix.config.name } }
    runs-on: ${ { matrix.config.os } }
    strategy:
      fail-fast: false
      matrix: 
        config: 
          - 
            name: "Ubuntu (GCC)"
           # artifact: Linux.tar.xz
           # build_type: Release
            cc: gcc
            cxx: g++
            os: ubuntu-latest
          -
            name: "Test"

    steps:
    - name: "Checkout repo branch"
      uses: actions/checkout@v3
    
    - name: "Setup CMake"
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.16.x'
    
    - name: "Report CMake version"
      shell: cmake -P {0}
      run: |
        message(STATUS "Using host CMake version: ${CMAKE_VERSION}")
    
